### PR TITLE
Update HTTPRequest.cs

### PR DESCRIPTION
**Pull request by Xlinka**
Updated HTTP NODE to use one HTTP CLIENT instead of instantiating a new one for each pulse

### CODE REVIEW

**Comment by Xlinka** [comment]
@Lexevolution

**Comment by Lexevolution** [comment]
I couldn't see why #131 was happening, since I was only reusing the `CloudXInterface.SafeHTTPClient`, which is the same httpClient that's used in the vanilla GET and POST string nodes. But if changing it to its own httpClient fixes the problem, then I guess it's fine.

**Comment by Xlinka** [comment]
Maybe we should add a neosplus safehttp client for neosplus usage?

**Comment by Lexevolution** [comment]
The only difference between the regular one and the "safe" one is that the "safe" one has a one minute timeout. Which can just be added by putting
```cs
client.Timeout = TimeSpan.FromMinutes(1);
```
directly after [this](https://github.com/Xlinka/NeosPlus/pull/141/files#diff-50bf1785aa483b51806323e220c3d30fc5879f97385b4daa4e1c64cdae93e026R28).

**Comment by Xlinka** [comment]
Odd

**Comment by Xlinka** [comment]
merging since it fixes issue will update if anything else arrises

**Pull request merged**
