### PR TITLE
Add more nodes that return slot collections (and add my Neos path to csproj)

### PR DESCRIPTION
**Pull request by Nytra**
Add GetAllParents and GetAllChildren nodes, GetChildrenWithName/Tag and GetParentsWithName/Tag. Also adds my Neos path to the .csproj.

### CODE REVIEW

**Comment by Xlinka** [comment]
has this been tested ?

**Comment by Nytra** [comment]
> has this been tested ?

I tested them myself briefly and they all seemed to work.

**Comment by Xlinka** [comment]
hello nytra just coming back round to all this are you available sometime to show me these.

**Comment by Xlinka** [comment]
@Frozenreflex want to review this since the collection stuff is your brain child

**Comment by Xlinka** [comment]
just went through and tested them these seem to work on my system

**Comment by Nytra** [comment]
Linka said the nodes here should be outputting ReadOnlyCollections instead of Lists. If this is the case then probably the existing GetChildrenWithTag LogiX node (which was previously merged) should be updated as well.

**Comment by Xlinka** [comment]
It's something @Frozenreflex said and I'm just wondering if I misinterpreted what they said or if we must do this wait till they reply

**Review by Frozenreflex — APPROVED** [review]

**Comment by Xlinka** [comment]
oof conflict tag @Nytra soryyy

**Comment by Nytra** [comment]
Fixed conflict, also fixed category strings and a couple of bugs

**Review by Xlinka — APPROVED** [review]

**Pull request merged**
