### PR TITLE
ParseEnum node

### PR DESCRIPTION
**Pull request by dfgHiatus**
There is probably a more efficient way of doing this, but I figured I'd take a stab at it. 

Related issue: https://github.com/Neos-Metaverse/NeosPublic/issues/3545

### CODE REVIEW

**Comment by dfgHiatus** [comment]
One thing to note: As enum parsing is relatively expensive in general, this will only update the "IsParsed" output once the input string has been changed. A simple workaround is to compare 2 enums

Screenshot

**Comment by Xlinka** [comment]
Just get @ProbablePrime opinion if possible if not then we will continue with how is.

**Comment by ProbablePrime** [comment]
What... why are you looping?

**Comment by ProbablePrime** [comment]
```
using System;
					
public class Program
{
	enum Season
	{
		Spring,
		Summer,
		Autumn,
		Winter
	}
	public static void Main()
	{
		Season result;
		var e = Enum.TryParse<Season>("Summer", out result);
		if (e)
		  Console.WriteLine(result.ToString());
        else
          Console.WriteLine("Cheese");
	}
}
```

What's the loop for?

**Comment by dfgHiatus** [comment]
In order to use `Enum.TryParse` we needed to extend `struct`. Read about this [here](https://stackoverflow.com/questions/17363336/the-type-string-must-be-a-non-nullable-value-type-in-order-to-use-it-as-parame)

**Comment by ProbablePrime** [comment]
```
using System;
using FrooxEngine.LogiX;

namespace FrooxEngine
{
    [Category(new string[] { "LogiX/Input" })]
    [GenericTypes(GenericTypes.Group.CommonEnums)]
    public class ParseEnum<E> : LogixOperator<E> where E Enum, IConvertible
    {
        public readonly Input<string> Canidate;
        public readonly Input<bool> IgnoreCase;
        public readonly Output<bool> IsParsed;

        public override E Content
        {
            get
            {
                E testEnum;
                IsParsed.Value = Enum.TryParse<E>(Canidate.EvaluateRaw(), IgnoreCase.EvaluateRaw(), out testEnum);
                return testEnum; // Logically equivalent to default(E), or the first item in an enumeration
            }
        }
    }
}
```
Works without the struct

**Comment by dfgHiatus** [comment]
On my end that isn't the case. I will defer to one of colleagues to confirm this works for them

**Comment by Frozenreflex** [comment]
It complains about struct on my end as well.

**Comment by ProbablePrime** [comment]
neos actual, doesnt complain, but either way it works, should be more performant too.

thanks for double checking

**Pull request merged**
