### PR TITLE
Add Find Grabbable LogiX Node

### PR DESCRIPTION
**Pull request by Nytra**
Takes a Slot input and returns the first Grabbable component in parents (as an IGrabbable) or null.

Useful for checking if a slot is grabbable, and also can be used with the other pre-existing Grabbable logix nodes.

### CODE REVIEW

**Comment by Nytra** [comment]
This is my first ever logix node so let me know if there are issues with it

**Comment by Xlinka** [comment]
Have you tested it and also any gh issues on main for this?, I'll check it when I wakeup later.

**Comment by Nytra** [comment]
I have tested it and it works, but I'm worried it might be unoptimized. Could it be calling GetComponent every frame? There are no GH issues for this that I could find.

**Comment by Nytra** [comment]
Changed node name to "Get Slot Grabbable" and optimized it maybe

**Comment by Nytra** [comment]
Updated node to find Grabbable in parents

**Review by Xlinka — COMMENTED** [review]
Overall, the code looks clean and concise. It performs its intended functionality of finding the IGrabbable component from a given Slot. Keep up the good work!

**Pull request merged**
